sudo: required
dist: trusty
language: cpp

compiler:
    - gcc
    - clang

# addons:
#     apt:
#         sources:
#             - llvm-toolchain-trusty
#         packages:
#             - clang-3.7

before_install:
    - sudo add-apt-repository -y ppa:kojoley/boost
    - sudo apt-get update -y || echo "update error"
    - wget -nv -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
    - sudo apt-add-repository -y 'deb http://llvm.org/apt/trusty llvm-toolchain-trusty-3.8 main'
    - sudo apt-get update -qq
    - sudo apt-get install -qq -y clang-3.8
    - lsb_release -a

install:
    - git clone https://github.com/yyzybb537/Boost-dev-bin.git /tmp/boost-dev-bin && sudo dpkg -i /tmp/boost-dev-bin/libboost1.59-all-dev.deb
    - ls /usr/local/lib/libboost*
    - sudo ldconfig
    - sudo apt-get install -y -qq cmake
    - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.8" CC="clang-3.8" COMPILER=clang++-3.8; fi
script:
    - mkdir build; pushd build;
    - cmake .. && make -j4 && sudo make install && make test_small && make tutorial && make run_test
    - sudo rm * -rf && cmake .. -DENABLE_BOOST_COROUTINE=ON -DWITH_SAFE_SIGNAL=ON && make -j4 && sudo make install && make test_small && make tutorial && make run_test
    - sudo rm * -rf && cmake .. -DENABLE_BOOST_COROUTINE=ON && make -j4 && sudo make install && make test_small && make tutorial && make run_test
    - sudo rm * -rf && cmake .. -DENABLE_BOOST_CONTEXT=ON && make -j4 && sudo make install && make test_small && make tutorial && make run_test
    - popd;

after_success:
    -

branches:
    only:
    - dev
    - master
    - clang-travis

notifications:
  email: true
